// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC193vg0eHySe9beX_FgaFupp8Dodvjmio',
    appId: '1:822893116304:web:eeea4d8253b79007cb5115',
    messagingSenderId: '822893116304',
    projectId: 'flutter-chat-c8161',
    authDomain: 'flutter-chat-c8161.firebaseapp.com',
    storageBucket: 'flutter-chat-c8161.appspot.com',
    measurementId: 'G-ZKCBZK8DG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD50oGcNHb6OcqT-2yCZCcXsJKYmgXbWA',
    appId: '1:822893116304:android:174b14f2bdcce368cb5115',
    messagingSenderId: '822893116304',
    projectId: 'flutter-chat-c8161',
    storageBucket: 'flutter-chat-c8161.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJV6wEEotwSuxG4cqC65aDGxBVuPFqABw',
    appId: '1:822893116304:ios:c58cdeb213804d17cb5115',
    messagingSenderId: '822893116304',
    projectId: 'flutter-chat-c8161',
    storageBucket: 'flutter-chat-c8161.appspot.com',
    iosClientId: '822893116304-h0jdirqvq3bp60281s6bgbfej7louj2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
