import 'package:flutter/material.dart';
// for the platform exception in catch
import 'package:flutter/services.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

import 'package:chat_app/widgets/auth_form.dart';

class AuthScreen extends StatefulWidget {
  const AuthScreen({Key? key}) : super(key: key);

  @override
  State<AuthScreen> createState() => _AuthScreenState();
}

class _AuthScreenState extends State<AuthScreen> {
  final auth = FirebaseAuth.instance;
  Future<void> _submitAuthForm(
    String email,
    String username,
    String password,
    bool isLogin,
    // ctx for the scaffold snackbar
    BuildContext ctx,
  ) async {
    UserCredential userCredential;
    try {
      if (isLogin) {
        userCredential = await auth.signInWithEmailAndPassword(
          email: email,
          password: password,
        );
      } else {
        userCredential = await auth.createUserWithEmailAndPassword(
          email: email,
          password: password,
        );
        // extra userdata when creating new user
        await FirebaseFirestore.instance
            .collection('users')
            // userCredential will have the user object
            // user will create uid field
            // uid is the user id will be generated by firebase for the user
            .doc(userCredential.user!.uid)
            // store extra data for that document
            // map with any key value pairs
            .set({
          'username': username,
          'email': email,
        });
      }
    }
    // Platform specific error
    on PlatformException catch (error) {
      var message = 'An error occured. Please check your credentials.';

      if (error.message != null) {
        message = error.message!;
      }

      // Showing the error message in bottom snack bar
      Scaffold.of(ctx).showSnackBar(
        SnackBar(
          content: Text(message),
          backgroundColor: Theme.of(context).errorColor,
        ),
      );
    }
    // on typical error
    catch (error) {
      print(error);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Theme.of(context).primaryColor,
      body: AuthForm(
        _submitAuthForm,
      ),
    );
  }
}
